### PR TITLE
Gen tracks for allegro

### PR DESCRIPTION
**Pull request by BrieucF**
- Migration to IOSvc in order to have Gaudi functionals properly outputting collections
 - Avoid calling `AuditExecute` everytime one adds an algorithm
 - Add Tracks from gen particle

### CODE REVIEW

**Comment by giovannimarchiori** [comment]
Nice! I guess it's not easy / worth spending time to avoid hardcoding Bz in the tracking module and taking it instead from the k4geo xml?

**Comment by BrieucF** [comment]
> Nice! I guess it's not easy / worth spending time to avoid hardcoding Bz in the tracking module and taking it instead from the k4geo xml?

This is on the to do list for the `TracksFromGenParticles` algorithm ;-)

**Comment by BrieucF** [comment]
Normally the test should pass tomorrow morning, let's see

**Comment by giovannimarchiori** [comment]
Retrying the tests

**Comment by BrieucF** [comment]
Tests are fixed :-)

**Comment by giovannimarchiori** [comment]
ok, let's merge this PR then!

**Pull request merged**
